CC		= i686-w64-mingw32-g++-win32
CXXFLAGS	= -Wall -O2 -s -static -static-libstdc++ -std=c++11
DEPS		= xmkit.h
OBJ		= xmkit.o xm2sleizsatrio.o


xm2sleizsatrio.exe: $(OBJ)
	$(CC) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

%.o: %.cpp $(DEPS)
	$(CC) -c $(CXXFLAGS) -o $@ $< $(LDFLAGS)

.PHONY: clean
clean:
	rm *.o
